CREATE EXTENSION IF NOT EXISTS unaccent; -- < Включает расширение для удаления диакритических знаков

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- id: название столбца, BIGINT: 64-битное целое число для большого диапазона значений
    -- GENERATED BY DEFAULT AS IDENTITY: автоинкремент, можно вставлять свои значения при необходимости
    -- PRIMARY KEY: основной ключ таблицы, уникальный идентификатор каждой записи
    title VARCHAR(255) NOT NULL,
    author VARCHAR(100),
    section VARCHAR(50) NOT NULL CHECK (
        section IN (
            'IT', 'Health', 'Finance', 'Lifestyle', 'Network', 'Spiritual'
        )
    ),
    -- CHECK (...): ограничение допустимых значений, гарантирует, что section (см. ниже)
    -- может быть только одной из перечисленных категорий ('IT', 'Health', 'Finance', 'Lifestyle', 'Network', 'Spiritual')
    format VARCHAR(50) NOT NULL CHECK (
        format IN (
            'Book', 'Article', 'Video', 'Audio'
        )
    ),
    studytime INTEGER NOT NULL CHECK (studytime IN (15, 30, 60, 90, 120)),
    link TEXT,
    normalized_title VARCHAR(255)
        GENERATED ALWAYS AS (
            lower(trim(unaccent(title))) -- игнорируем регистр(убираем пробелы(игнорируем диакритику(заголовка))
        ) STORED
    CONSTRAINT normalized_title_unique UNIQUE (normalized_title) -- Уникальность ЛОГИЧЕСКОГО названия
);

